# Generated by Django 4.2.29 on 2026-04-28 14:18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
