# Generated by Django 6.0.4 on 2026-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_card_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.IntegerField(choices=[(860, 'UZS'), (643, 'RUB'), (840, 'USD')]),
        ),
    ]
