# Generated by Django 5.2.13 on 2026-04-26 08:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_transfer_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receiver_card_number',
            field=models.CharField(max_length=16),
        ),
    ]